# MkDocs configuration for FPsim
# https://www.mkdocs.org/user-guide/configuration/

site_name: FPsim
site_description: Agent-based model for family planning research
site_url: https://docs.fpsim.org

repo_name: fpsim/fpsim
repo_url: https://github.com/fpsim/fpsim
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Gates Foundation. All rights reserved.

theme:
  name: material
  font:
    text: Raleway
    code: Roboto Mono
  logo: assets/starsim-logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer # include a footer with links to privacy, terms, etc.
    - content.code.copy # enable copy buttons for code blocks
    - navigation.indexes # enable parent index page for sections
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: cyan
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: cyan

nav:
  - Home: index.md
  - Overview: overview.md
  - Tutorials:
      - Tutorials index: tutorials.md
      - T1 Introduction: tutorials/T1_intro.ipynb
      - T2 New features: tutorials/T2_intro_to_new_features.ipynb
      - T3 Interventions and methods: tutorials/T3_interventions_methods.ipynb
      - T4 Intervention eligibility: tutorials/T4_intervention_eligibility.ipynb
      - T5 Adding a new method: tutorials/T5_new_method.ipynb
  - What's new: whatsnew.md
  - Code of conduct: code_of_conduct.md
  - Contributing: contributing.md
  - API reference: api.md

# docs_dir is implicit default "docs"
docs_dir: docs

# icons, semantic markup, emojis
markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list # enables HTMl and CSS classes to inline elements
  - md_in_html # enables grids
  - admonition # warnings, etc.
  - def_list
  - footnotes

# javascript customization for math
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - customization/css/extra.css # custom CSS for footer spacing

plugins:
  # Process notebooks first so they are converted and included in the build
  - mkdocs-jupyter:
      include: ["**/*.ipynb"]
      execute: true
      allow_errors: true
      include_source: true
      kernel_name: python3
  - search
  - autorefs
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [.] # path to source code
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            heading_level: 2
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true
            show_object_full_path: true

extra:
  generator: false
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fpsim/fpsim
    - icon: fontawesome/regular/envelope
      link: mailto:info@starsim.org
    - icon: fontawesome/brands/slack
      link: https://starsim-idm.slack.com
    - icon: octicons/globe-24
      link: https://fpsim.org

  analytics:
    property: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
